Dev 2794
Erwann20/RTL-formation pull request #2
Opened 2024-02-20 15:17 UTC by codinHamster

2024-02-20 16:13 UTC, Erwann20 requested changes

2024-02-20 16:13 UTC, Erwann20 commented on src/Counter/Counter.test.tsx
> +
Super ! Tu as bien compris le concept de test c'est cool :)

Si tu regardes le coverage en faisant: yarn test:cov

Tu vas voir que tes tests ne couvrent pas toute tous le code notamment cette partie:

![image](https://github.com/Erwann20/RTL-formation/assets/38038867/dae08181-c37a-4954-a65f-cc985a733c9d)

2024-02-20 16:13 UTC, Erwann20 commented on src/Counter/Counter.util.test.ts
> +        const expectResult = '123'
C'est parfait pour aller encore plus loin tu peux tester aussi pour un chiffre négatif en plus du test par 123 :)

2024-02-21 09:43 UTC, Erwann20 requested changes

2024-02-21 09:43 UTC, Erwann20 commented on coverage/.tmp/coverage-0.json
> +{"result":[{"scriptId":"1203","url":"file:///Users/hmd/projects/formation/RTL-formation/src/Counter/Counter.util.test.ts","functions":[{"functionName":"","ranges":[{"startOffset":0,"endOffset":2216,"
N'oublie pas de push la suppression du dossier coverage :)

2024-02-21 09:43 UTC, Erwann20 commented on src/Counter/Counter.util.test.ts
> +  it("formatNumberToString", () => {
Dans un test, on va utiliser des describes pour regrouper un ensemble de tests qui concerne une partie du code.
Dans ce cas ici on devrait avoir cette structure: 

```
describe("Unit::Counter.util", () => {
   describe("formatNumberToString", () => {
         it("should ....") => {
 ....
```
Met à jour le code pour respecter cette structure :)

2024-02-21 09:50 UTC, codinHamster commented on coverage/.tmp/coverage-0.json
> +{"result":[{"scriptId":"1203","url":"file:///Users/hmd/projects/formation/RTL-formation/src/Counter/Counter.util.test.ts","functions":[{"functionName":"","ranges":[{"startOffset":0,"endOffset":2216,"
Pourtant coverage a bien été ajouté au fichier gitignore afin de l'ignorer.
Je l'avais écris sous cette forme /coverage et j'ai essayé avec coverage seul. Et là je voulais tenter avec coverage/

2024-02-21 09:51 UTC, codinHamster commented on src/Counter/Counter.util.test.ts
> +  it("formatNumberToString", () => {
D'accord. Je mets à jour ça.

2024-02-21 12:31 UTC, Erwann20 commented
@codinHamster c'est validé pour moi ! Bravo :tada:

2024-02-21 12:32 UTC, Erwann20 commented
@codinHamster c'est validé pour moi ! Bravo 🎉

2024-02-21 12:32 UTC, closed without merging